version: '3'
services:
  nginx:
    image: armyguy255a/nginx:latest

    ports:
      - 80:80
      - 443:443
    volumes:
    - /var/www/:/var/www/
    - /etc/nginx/:/etc/nginx/
    - /var/log/nginx/:/var/log/nginx/
    - /etc/ssl/certs:/etc/ssl/certs