#requires -Version 7.0
<#
.SYNOPSIS
    One-time Terraform-state bootstrap for the appeid-edge footprint.

.DESCRIPTION
    Creates the resource group + storage account + container that the
    `terraform/prod` configuration uses as its azurerm state backend, then
    writes ../prod/backend.prod.hcl with the resulting names so subsequent
    `terraform init -backend-config=backend.prod.hcl` calls just work.

    Idempotent: re-running against existing resources is a no-op except
    for re-emitting backend.prod.hcl.

.PARAMETER SubscriptionId
    Azure subscription to provision state in. Defaults to the PhotoGallery
    subscription (override if you want isolation).

.PARAMETER Location
    Region for the state account. Defaults to eastus2.

.PARAMETER ResourceGroup
    State resource group name. Defaults to appeid-tfstate.

.PARAMETER StateAccount
    Storage account name. If omitted, derives a globally unique name with
    a 4-char random suffix.
#>
[CmdletBinding()]
param(
    [string] $SubscriptionId = "4fc243fa-5de2-48cb-9c98-793701d13152",
    [string] $Location       = "eastus2",
    [string] $ResourceGroup  = "appeid-tfstate",
    [string] $StateAccount,
    [string] $Container      = "tfstate"
)

$ErrorActionPreference = "Stop"

function Invoke-Az {
    param([Parameter(ValueFromRemainingArguments)] $Args)
    & az @Args
    if ($LASTEXITCODE -ne 0) { throw "az $($Args -join ' ') exited $LASTEXITCODE" }
}

Write-Host "[1/4] Targeting subscription $SubscriptionId" -ForegroundColor Cyan
Invoke-Az account set --subscription $SubscriptionId

Write-Host "[2/4] Ensuring resource group $ResourceGroup in $Location" -ForegroundColor Cyan
Invoke-Az group create --name $ResourceGroup --location $Location --output none

if (-not $StateAccount) {
    $suffix = -join ((97..122) | Get-Random -Count 4 | ForEach-Object { [char]$_ })
    $StateAccount = "tfstateappeid$suffix"
}

Write-Host "[3/4] Ensuring storage account $StateAccount" -ForegroundColor Cyan
$exists = az storage account show --name $StateAccount --resource-group $ResourceGroup --query name -o tsv 2>$null
if (-not $exists) {
    Invoke-Az storage account create `
        --name $StateAccount `
        --resource-group $ResourceGroup `
        --location $Location `
        --sku Standard_LRS `
        --kind StorageV2 `
        --min-tls-version TLS1_2 `
        --allow-blob-public-access false `
        --output none
    Invoke-Az storage account blob-service-properties update `
        --account-name $StateAccount `
        --resource-group $ResourceGroup `
        --enable-versioning true `
        --output none
}

Write-Host "[3.5/4] Ensuring container $Container" -ForegroundColor Cyan
Invoke-Az storage container create `
    --name $Container `
    --account-name $StateAccount `
    --auth-mode login `
    --output none

$backendFile = Join-Path $PSScriptRoot "..\prod\backend.prod.hcl"
Write-Host "[4/4] Writing $backendFile" -ForegroundColor Cyan
@"
# Generated by terraform/bootstrap/bootstrap-state.ps1 on $(Get-Date -Format o)
resource_group_name  = "$ResourceGroup"
storage_account_name = "$StateAccount"
container_name       = "$Container"
key                  = "appeid-edge-prod.tfstate"
"@ | Set-Content -Path $backendFile -Encoding utf8

Write-Host ""
Write-Host "Done. Next:" -ForegroundColor Green
Write-Host "  cd ..\prod"
Write-Host "  terraform init -backend-config=backend.prod.hcl"
Write-Host "  terraform apply -var ""swa_upstream=<SWA default hostname>"""
